### ISSUE TITLE
TIme picker is not responding

### ISSUE THREAD

**Issue by MnParel** [tungxuan1656/react-native-tx-modern-datetimepicker#1]
Hi,

Can't choose the time from picker. It always focuses on the 0h and 0 min. Here is my code

<Modal
      transparent={true}
      animationType="fade"
      visible={isShown}
      supportedOrientations={['portrait']}
      onRequestClose={() => onHide()}>
      <View
        style={{
          flex: 1,
          backgroundColor: Colors.modalOverlayDarkBackgroundVariant,
        }}>
        <TouchableHighlight
          underlayColor={'transparent'}
          style={styles.modalContainer}
          activeOpacity={1}
          onPress={() => onHide()}>
          <View style={styles.modalSubContainer}>
            <DatePicker
              onDateChange={date => setDate(date)}
              options={{
                backgroundColor: '#090C08',
                textHeaderColor: '#FFA25B',
                textDefaultColor: '#F6E7C1',
                selectedTextColor: '#fff',
                mainColor: '#F4722B',
                textSecondaryColor: '#D6C7A1',
                borderColor: 'rgba(122, 146, 165, 0.1)',
              }}
              current="2020-07-13"
              selected="2020-07-23"
              mode="dateTimePicker"
              style={{borderRadius: 10}}
            />
          </View>
        </TouchableHighlight>
      </View>
    </Modal>

**Comment by tungxuan1656** [comment]
Hi, I just checked, now you can still choose the time, you can get it by calling the onTimeChange callback.

**Comment by tungxuan1656** [comment]
Also, I also found out that currently doesn't allow initialization of input time using **selected**, I'll upgrade it by the end of the week

**Comment by MnParel** [comment]
Hi,  Thanks for the quick response. The callback methods are working fine. My problem is regarding the scrolling of time picker. I can't scroll the picker to choose the hour and minute. 

for more detail pls find the style I used,

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
    height: 50,
    flexDirection: 'row',
  },
  btnTxt: {
    position: 'absolute',
    top: 0,
    height: 42,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnCancel: {left: 0},
  btnDone: {right: 0},
  pickerDateContainer: {
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  pickerDate: {
    fontSize: 18,
    color: 'black',
  },
  modalContainer: {
    flex: 1,
    // flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubContainer: {
    width: '100%',
    // height: 'auto',
    paddingHorizontal: Spacing.large,
  },
  pickerContainer: {
    backgroundColor: 'white',
    overflow: 'hidden',
    borderTopColor: '#E9E9E9',
    borderTopWidth: 1,
    height: Platform.OS === 'ios' ? windowHeight / 3.2 : windowHeight / 3.5,
  },
});


Could you check this please

**Comment by tungxuan1656** [comment]
I think you should try it the way I use it in the example. 
Then you can think about customizing the ui and putting it inside the modal. 
I just updated to a new version for my npm package. It is now possible to initialize with the time value, the time picker will also continue at the previously selected value
